### ISSUE TITLE
sqlalchemy.exc.OperationalError: (OperationalError) no such table

### ISSUE THREAD

**Issue by zjuguxi** [miguelgrinberg/flasky#168]
Hello Miguel, I've finished your book and tried to build a "notebook" project without the help of the book. "Notebook" is a simplified flasky, no User, no Role, no Migrate, No Manage, just Post. 

I thought it would be easy, and everything went well until I added these two lines in views.py:
`posts = Post.query.order_by(Post.timestamp.desc()).all()
    return render_template('index.html', current_time = datetime.utcnow(), form = form, posts = posts)`
I got the following error:
`sqlalchemy.exc.OperationalError: (OperationalError) no such table`

I read issue #18, but still can't solve my problem(I didn't use manager to modify the command line). 
Could you please tell me what's wrong with it?
Thank you !!

Here's my code:

run.py

```
# -*- coding:utf-8 -*-
from app import create_app
app = create_app()
if  __name__ == '__main__':
     app.run(debug = True)
```

**init**.py

```
from flask import Flask
from flask_sqlalchemy import SQLAlchemy 
from flask_moment import Moment
from flask_bootstrap import Bootstrap


moment = Moment ()
bootstrap = Bootstrap()
db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    moment.init_app(app)
    bootstrap.init_app(app)
    app.secret_key = 'SECRET_KEY'
    db.init_app(app)
    with app.app_context():
           db.create_all()

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app
```

views.py

```
from flask import render_template, redirect, url_for, session
from datetime import datetime
from . import main
from app.forms import PostForm
from flask_login import current_user
from ..models import Post


@main.route('/', methods = ['GET', 'POST'])
def index():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(body = form.body.data)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('.index'))
    posts = Post.query.order_by(Post.timestamp.desc()).all()
    return render_template('index.html', current_time = datetime.utcnow(), form = form, posts = posts)

@main.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404
```

**Comment by miguelgrinberg** [comment]
The error is pretty clear, you have not created the database table. You have defined the model, but then a table that matches that model needs to be created in the database. If you are using migrations, then you will have migration that creates the table. If you are not using migrations, then you have to call `db.create_all()` to create your tables. This is covered near the beginning of the book, before migrations are introduced.

**Comment by zjuguxi** [comment]
Thanks Miguel.
I tried as you said, and it's still unable to create the database. Then I added the following lines in **run.py**:
```
app.config['SECRET_KEY'] = 'hard to guess string'
app.config['SQLALCHEMY_DATABASE_URI'] =\
    'sqlite:///' + os.path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_COMMIT_ON_TEARDOWN'] = True
```
Finally it worked. 
But it makes me more confused. I did define the path of database in config.py. Why do I have to do it again in run.py? Any mistake in my code?

**config.py**
```
import os
basedir = os.path.abspath(os.path.dirname(__file__))

class Config:
    SECRET_KEY = os.environ.get('SECRET_KEY') or 'hard to guess string'
    SQLALCHEMY_COMMIT_ON_TEARDOWN = True
    @staticmethod
    def init_app(app):
        pass

class DevelopmentConfig(Config):
    DEBUG = True
    SQLALCHEMY_DATABASE_URI = os.environ.get('TEST_DATABASE_URL') or \
        'sqlite:///' + os.path.join(basedir, 'data.sqlite')


class TestingConfig(Config):
    TESTING = True
    SQLALCHEMY_DATABASE_URI = os.environ.get('TEST_DATABASE_URL') or \
        'sqlite:///' + os.path.join(basedir, 'data-test.sqlite')


class ProductionConfig(Config):
    SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL') or \
        'sqlite:///' + os.path.join(basedir, 'data.sqlite')


config = {
    'development': DevelopmentConfig,
    'testing': TestingConfig,
    'production': ProductionConfig,

    'default': DevelopmentConfig
}
```

**Comment by miguelgrinberg** [comment]
In your `create_app` function you have to read the configuration. I think [this line](https://github.com/miguelgrinberg/flasky/blob/master/app/__init__.py#L23) is what you are missing.

**Comment by zjuguxi** [comment]
Yeah you're right. My problem is solved. Many thanks for your help!
Obviously I need to review your book.....

**Comment by tiansiyuan** [comment]
Without the following code, I got the same error.

with app.app_context():
           db.create_all()

It is not in the original repository.

**Comment by tiansiyuan** [comment]
I guess it is done by 

python manage.py db init

**Comment by 54lazycat** [comment]
My code is like your's. But my code still not work.I am confuse that in the init file ,the code execute db.create_all().but why the table did not create ? btw I don't use migration.

**Comment by Owlish85** [comment]
it's my simply code but:




``from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import *




app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:////Users/Sami/Desktop/TodoApp/todo.db'
db = SQLAlchemy(app)


class Todo(db.Model):    
    id = db.Column(db.Integer,primary_key=True)
    title = db.Column(db.String(80))
    complete = db.Column(db.Boolean)

if __name__ == "__main__":
    db.create_all()
    app.run(debug=True)




But any time i take this. please some one help me::::

**Comment by ozer619** [comment]
hello sir, i also got the same error of operational error i am using migrations and and i also used flask upgrade when i am opening the sqlite3 file .schema it is showing users tabel but when i run the application it says tabel not found

**Comment by Jhonathan-Pedroso** [comment]
This error happen even with the original git checkout 7a. I would recommend update this into the repository, I guess it is causing confusion in everyone new to web development.

**Comment by ANAS3133** [comment]
i have same problem
