### ISSUE TITLE
Errata: if current_user.is_authenticated()

### ISSUE THREAD

**Issue by leonardocintra-luizalabs** [miguelgrinberg/flasky#82]
`Tag: 12a`

In the book the `if current_user.is_authenticated()` field in template `user.html` contains parentheses.
The correct thing without the parenthesis.

Cause the error:
![image](https://cloud.githubusercontent.com/assets/10760131/10494354/536a9d50-728c-11e5-8ab4-edef00a849f8.png)

The code on GitHub is correct :+1: 

Ps: My English is very poor! Sorry!

**Comment by miguelgrinberg** [comment]
@leonardocintra-luizalabs This is unfortunately, but Flask-Login refactor a number of methods as properties after the book was published. I have updated the code in this repository, and also included a mention in the book errata I keep at http://flaskbook.com.

**Comment by justvidyadhar** [comment]
Just realised that this is a persistent error in app/auth/views.py from 8-22.

**Comment by miguelgrinberg** [comment]
I think I have updated all in this repository, but you need to refresh your copy or re-clone to see these updates. Or did you find one that I missed?

**Comment by justvidyadhar** [comment]
Just fetched all updates from repo. The error still seems to persist at commit 8e. Havent checked further. Will update here if it exists in further commits too.
